// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateKVClient(arg1:string):Promise<void>;

export function GetKilovoltBind():Promise<string>;

export function IsServerReady():Promise<boolean>;
