// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateKVClient(arg1) {
  return window['go']['main']['App']['AuthenticateKVClient'](arg1);
}

export function GetKilovoltBind() {
  return window['go']['main']['App']['GetKilovoltBind']();
}

export function GetTwitchAuthURL() {
  return window['go']['main']['App']['GetTwitchAuthURL']();
}

export function GetTwitchLoggedUser() {
  return window['go']['main']['App']['GetTwitchLoggedUser']();
}

export function IsServerReady() {
  return window['go']['main']['App']['IsServerReady']();
}
