// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AuthenticateKVClient(arg1) {
  return window['go']['main']['App']['AuthenticateKVClient'](arg1);
}

export function GetAppVersion() {
  return window['go']['main']['App']['GetAppVersion']();
}

export function GetBackups() {
  return window['go']['main']['App']['GetBackups']();
}

export function GetDocumentation() {
  return window['go']['main']['App']['GetDocumentation']();
}

export function GetKilovoltBind() {
  return window['go']['main']['App']['GetKilovoltBind']();
}

export function GetLastLogs() {
  return window['go']['main']['App']['GetLastLogs']();
}

export function GetTwitchAuthURL() {
  return window['go']['main']['App']['GetTwitchAuthURL']();
}

export function GetTwitchLoggedUser() {
  return window['go']['main']['App']['GetTwitchLoggedUser']();
}

export function IsFatalError() {
  return window['go']['main']['App']['IsFatalError']();
}

export function IsServerReady() {
  return window['go']['main']['App']['IsServerReady']();
}

export function RestoreBackup(arg1) {
  return window['go']['main']['App']['RestoreBackup'](arg1);
}

export function SendCrashReport(arg1, arg2) {
  return window['go']['main']['App']['SendCrashReport'](arg1, arg2);
}
