// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {map[string]docs} from '../models';
import {helix} from '../models';

export function AuthenticateKVClient(arg1:string):Promise<void>;

export function GetAppVersion():Promise<main.VersionInfo>;

export function GetDocumentation():Promise<map[string]docs.KeyObject>;

export function GetKilovoltBind():Promise<string>;

export function GetLastLogs():Promise<Array<main.LogEntry>>;

export function GetTwitchAuthURL():Promise<string>;

export function GetTwitchLoggedUser():Promise<helix.User>;

export function IsServerReady():Promise<boolean>;
